refactor: noria rename
cdbo/cdnode pull request #6
Opened 2023-03-06 06:01 UTC by jumpdest7d

Yo @matpb 

Please give this PR a big once-over. Thank you!

2023-03-06 17:38 UTC, matpb requested changes
Great work on the refactor! 
Please review my comments and address any required changes.

2023-03-06 17:38 UTC, matpb commented on README.md
>  - Staking denom: `unoria`
We probably should add that the fee denom is `ucrd`.

2023-03-06 17:38 UTC, matpb commented on README.md
>  # Chain Specs
In this section, we should add the fees denom and its total initial supply. Should probably have @FrankBoltzmann  chime in here.

2023-03-06 17:38 UTC, matpb commented on README.md
>  `app.toml`
The `minimum-gas-prices` should be `0.0025ucrd`

2023-03-06 17:38 UTC, matpb commented on README.md
>  ```bash
the `--gas-prices` flag should be in ucrd for any example txs in the readme.

2023-03-06 17:38 UTC, matpb commented on README.md
>  --gas-prices="0.0025unoria" \
the `--gas-prices` flag should be in ucrd for any example txs in the readme.

2023-03-06 17:38 UTC, matpb commented on app/const.go
> +	UpgradeName = "v0.1.0"
Have we put some thoughts into the versionning of the noriad?
I'm personally much more a fan of starting at 1.0.0, but I won't fight this very hard.

My main reasoning being demonstrating confidence in the code, showing it as a production-ready binary, as compared to sub-1.0.0 versions which are often interpreted (even wrongly) as beta.

my 2 cents.

2023-03-06 17:38 UTC, matpb commented on app/const.go
> +	UpgradeName = "v0.1.0"
That being said, we have to make sure that whichever version we set as the initial `UpgradeName` is the actualy on-chain version at genesis.

2023-03-06 17:38 UTC, matpb commented on config.yml
> +  chain_id: "oasis-3"
This file will require a lot more changes; we can go through it together during a live session.

2023-03-06 17:38 UTC, matpb commented on genesis.json
> +  "chain_id": "oasis-3",
We will need a whole new genesis file that we will generate from ignite and manually modify.

2023-03-06 17:38 UTC, matpb commented on scripts/chain_upgrade.sh
>  DENOM="unoria"
We will need a new var for GAS_DENOM since it will be ucrd, while the deposit will still be unoria.

2023-03-06 17:38 UTC, matpb commented on scripts/init_local.sh
>  DENOM="unoria"
We will need a new var for GAS_DENOM since it will be ucrd.

2023-03-06 17:38 UTC, matpb commented on scripts/init_local.sh
> +echo -e "\n\nYou can now start your chain with 'noriad start'\n"
Some params will need to change here, to reflect the new minimum-has-prices. We can leave the dev voting period as short as it is there, since this script is for local dev purposes.

2023-03-06 17:38 UTC, matpb commented on txTest/setEnv.sh
> +export TX_PARAMS='--gas auto --gas-prices 0.0025unoria --gas-adjustment 1.75 --chain-id oasis-3'
Fees denom should be ucrd. Adjustment could be lowered to `1.3`.

2023-03-06 17:38 UTC, matpb commented on txTest/upgrade.sh
>  DENOM="unoria"
We will need a new var for GAS_DENOM since it will be ucrd.

2023-03-07 17:44 UTC, jumpdest7d commented on app/const.go
> +	UpgradeName = "v0.1.0"
@matpb I also like starting at 1.0.0 - I'm not a fan of 0.anything if it's handling production workloads. I've added this as an agenda item for us to discuss in our Eng Weekly today.

2023-03-07 17:45 UTC, jumpdest7d commented on config.yml
> +  chain_id: "oasis-3"
@matpb let's schedule one during our Eng Weekly, or do it right after.

2023-03-07 17:45 UTC, jumpdest7d commented on scripts/chain_upgrade.sh
>  DENOM="unoria"
I've added a new var called GAS_PRICE_DENOM and set it to "ucrd"

2023-03-07 17:57 UTC, matpb commented on README.md
>  # Chain Specs
@FrankBoltzmann confirmed that the total supply of NORIA will be 250M, so is the DENOM on testnet.

2023-03-07 17:58 UTC, matpb approved these changes

2023-03-08 05:17 UTC, merged